### ISSUE TITLE
public/images should also be writable

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#20]
Not included in the copy paste SETUP.md ;-)

**Comment by pietercolpaert** [comment]
`mkdir public/images`

**Comment by ghost** [comment]
It isn't included at the top or in the ez-mode command, but it is mentioned here:
https://github.com/openknowledgebe/W4P/blob/develop/SETUP.md#write-access

I've made adjustments to the .gitignore folder so that the /images folder & its .gitkeep are also committed so you won't have to create this folder after you clone the repo. 

See also: https://github.com/openknowledgebe/W4P/tree/develop/public
