### ISSUE TITLE
SMTP information: not tested with right config

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#21]
When you use the wizard to install it, and when you first filled out something wrong in the SMTP fields, press forward, see an error, correct your mistake, and then press forward again, you just get the same error over again.

Probably, the test is executed with the previous configuration instead of the current configuration, yet the fields will be stored in the database, so the next time, you will actually get the right thing?

**Comment by ghost** [comment]
Nice catch. Ah yes, I think I've figured out why this happens. 

Because the config is stored in the database, I decided it's best that the latest email config is loaded in the AppServiceProvider. Thing is, this is the first thing that happens when the app boots (when a request comes in), so if the config is updated -- this happens after booting the AppServiceProvider, thus the old one is loaded -- the new email config is not overwritten. I'll fix this.

**Comment by pietercolpaert** [comment]
Exactly what I thought ;)

**Comment by ghost** [comment]
Okay, this should be fixed.
