### ISSUE TITLE
Support this project enhancement

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#28]
If we want to get users to fund us, every extra step will keep them from clicking the fund button.
### Problem

![screenshot from 2016-03-14 11-52-06](https://cloud.githubusercontent.com/assets/347073/13742312/6f26c34a-e9db-11e5-82c3-66403e583df7.png)

Over here, they need to enter their own amount of money they want to fund, without having an overview of the perks.
### Suggestion

Yet, they just want a "tier" or "perk", so I would suggest to add the description of each tier here and allowing people to select/deselect them. Next to the "next" button, you can add the total amount of financial investments with the currently selected perks.

**Comment by ghost** [comment]
I think this a good idea. That's also how Kickstarter does things. 

This page in particular wasn't finished either way (you can still see the "radial progress" placeholder text where the progress circles need to appear) so I'll keep this in the back of my mind when I start working on this page again.

**Comment by ghost** [comment]
I've added reward tier selection:

![screen shot 2016-03-18 at 11 46 46](https://cloud.githubusercontent.com/assets/13518991/13875595/214194ee-ecff-11e5-8dcf-fbdee3f7477b.png)
- If you select a tier, the price is adjusted
- If you enter a custom value, the correct tier corresponding to the value is highlighted

As always, since JS has been changed, don't forget to run `composer dump && gulp`
