### ISSUE TITLE
Markdown fields for non techies

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#33]
Quick and great fix:

Use https://simplemde.com/ for these fields

**Comment by ghost** [comment]
Great idea. I'll need to check if it breaks drag 'n drop uploads, though. On it.

**Comment by ghost** [comment]
I'm going to leave this for now, since it seems to break the drag and drop uploads. Also, the Bootstrap styling seems to override the editor's styling as well.

![screen shot 2016-03-15 at 12 10 25](https://cloud.githubusercontent.com/assets/13518991/13775832/132937cc-eaa7-11e5-987d-a9cfdda5d347.png)

**Comment by pietercolpaert** [comment]
Ok, obviously this is not of the highest priority. Don't worry!

**Comment by Dobbelsteen** [comment]
http://www.codingdrama.com/bootstrap-markdown/

Been experimenting with this markdown editor, it's compatible with the drag-and-drop upload features, but requires some setup. I'll attempt to implement it cleanly next week.
