### ISSUE TITLE
Manage donations in the Backend

### ISSUE THREAD

**Issue by Dobbelsteen** [openknowledgebe/W4P#42]
Currently the only confirmation required for a donation is that the donor him/herself confirms via the e-mail recieved.
Project owners have no influence over these donations, this means that a malicious person could "donate" all the materials for example, without actually donating, and the project owner can't remove these "bad" donations.

Pretty easy fix would be to add a deleted_at field in the donations table and a couple of extra functions to softdelete/undelete donations.

**Comment by ghost** [comment]
![screen shot 2016-03-30 at 17 20 41](https://cloud.githubusercontent.com/assets/13518991/14147433/c4ea451e-f69b-11e5-8dfe-a42d82f0411f.png)

I've made it so that you can manage donations on the "All donations" page. If you hide a donation, it's hidden everywhere except on that page. If the row is red, that donation is hidden. Hidden donations do **not count towards any goals** (they can be effectively treated as 'deleted' or 'hidden', whatever your prefer).

For this to work on existing installations, you'll need to perform the migration that adds the `deleted_at` column to this project.
