### ISSUE TITLE
Twitter card not valid

### ISSUE THREAD

**Issue by pietercolpaert** [openknowledgebe/W4P#46]
![screenshot from 2016-04-06 20-01-08](https://cloud.githubusercontent.com/assets/347073/14327448/a1e0155c-fc32-11e5-92bc-b5ebd75c3a8d.png)

Try for yourself at https://cards-dev.twitter.com/validator

**Comment by pietercolpaert** [comment]
Is it because I should have https enabled on my server?

**Comment by pietercolpaert** [comment]
Nope: now running https, yet doesn't work

**Comment by pietercolpaert** [comment]
Found the problem: we need a different player URL according to the twitter guidelines. E.g., those in the vimeo page itself are like this:

``` html

  <meta name="description" content="This is &quot;Ontdek Spitsgids&quot; by openknowledgebe on Vimeo, the home for high quality videos and the people who love them.">
  <meta name="twitter:card" content="player">
  <meta name="twitter:site" content="@vimeo">
  <meta name="twitter:title" content="Ontdek Spitsgids">
  <meta name="twitter:description" content="This is &quot;Ontdek Spitsgids&quot; by openknowledgebe on Vimeo, the home for high quality videos and the people who love them.">
  <meta name="twitter:image" content="https://i.vimeocdn.com/video/563569402_1280x720.webp">
  <meta name="twitter:player" content="https://player.vimeo.com/video/161353782">
  <meta name="twitter:player:width" content="1280">
  <meta name="twitter:player:height" content="720">
  <meta name="twitter:app:name:iphone" content="Vimeo">
  <meta name="twitter:app:id:iphone" content="425194759">
  <meta name="twitter:app:url:iphone" content="vimeo://app.vimeo.com/videos/161353782">
  <meta name="twitter:app:name:ipad" content="Vimeo">
  <meta name="twitter:app:id:ipad" content="425194759">
  <meta name="twitter:app:url:ipad" content="vimeo://app.vimeo.com/videos/161353782">
  <meta name="twitter:app:name:googleplay" content="Vimeo">
  <meta name="twitter:app:id:googleplay" content="com.vimeo.android.videoapp">
  <meta name="twitter:app:url:googleplay" content="vimeo://app.vimeo.com/videos/161353782">
```

Be more like the vimeo page! :)

**Comment by ghost** [comment]
Okay, I've changed it that the `twitter:player` property changes to:
- https://www.youtube.com/embed/XXXXXX
- https://player.vimeo.com/video/XXXXXX

Note that of course these URLs depend on the video provider.

The `twitter:image` property has also been changed to be the URL for the thumbnail image for that video. For YouTube, this was a straightforward process (appending the ID to a URL), for Vimeo less so. For Vimeo, getting the thumbnail URL requires an API request. (Fortunately, no auth required.)

What happens now, is that we request the Vimeo thumbnail URL every time you update your project. The Vimeo thumbnail URL is then saved in the database (otherwise we'd need to request it every time!) and outputted. You'll see a warning on the project page if the thumbnail could not be requested.

Can you check if the cards are valid now?

**Comment by pietercolpaert** [comment]
I would make the twitter:image configurable to be honest: this is what's going to appear when you're not yet seeing the video? I think it's pretty crucial to convince people to click the damn button ;)

Checking now! Be right back at you

**Comment by pietercolpaert** [comment]
Works like a charm now! 
![screenshot from 2016-04-07 11-13-53](https://cloud.githubusercontent.com/assets/347073/14346304/eb73e12e-fcb1-11e5-9526-e140b7851d1a.png)

**Comment by ghost** [comment]
Great to see it's working.

About a customizable `twitter:image`. The guidelines say this:

> Image to be displayed in place of the player on platforms that don’t support iframes or inline players. You should make this image the same dimensions as your player. Images with fewer than 68,600 pixels (a 262x262 square image, or a 350x196 16:9 image) will cause the player card not to render. Image must be less than 1MB in size.

I'm pretty sure almost all devices can show embedded video :) 

I also think choosing a custom image can be misleading because this image should represent the video (or at least the embed).

Also noteworthy: Twitter cards don't expand by default, so the title is far more important. (And you _can_ customize that.)

**Comment by pietercolpaert** [comment]
Fair enough! I consider this issue fixed! ^^
