### ISSUE TITLE
Create progress functionality

### ISSUE THREAD

**Issue by tthoeye** [openknowledgebe/W4P#7]
Each contribution category (money, people, material, skills) should get a weight in the backend which determines for how many % of total progress the category counts, default: each 25%

**Comment by ghost** [comment]
In addition to the weight for the contribution categories: should it be possible for contribution category subitems to have a weight?

Let's say we need 4 coaches, 3 junior devs and 1 senior dev. I assume that the senior dev's weight could potentially be adjusted, which influences the percentages (progress) here:

<img width="617" alt="screen shot 2016-02-02 at 18 32 23" src="https://cloud.githubusercontent.com/assets/13518991/12758122/542915d6-c9db-11e5-8ceb-4184f6cd9bc5.png"> 
_(Image from design, not illustrating the example)_

Because right now, for the example above with the junior devs and senior dev, I assume there are 2 categories, so each subcategory weighs in at 50%. (That means that having 1 senior dev will fill it up halfway.) Since we're looking for 4 people however (in this example), the weight could be adjusted to be 3-1 (by using a custom weight field or using the required amount of units as weight).

Does the weight for subitems need to be included? And if so, would you prefer a custom weight field or just use the required amount of units? (Personally, I would go for a custom field.)
