### ISSUE TITLE
Previous projects currency border grey despite 100% (or more) reached.

### ISSUE THREAD

**Issue by wesobi** [openknowledgebe/W4P#74]
if you add spitsgids to your previous projects (through the importer), you will notice that the "border' around the circle is grey despite being 100% reached.

![schermafbeelding 2016-05-18 om 18 11 23](https://cloud.githubusercontent.com/assets/9094522/15366317/0ca2feba-1d24-11e6-8acc-9ff1a668849b.png)

I also noticed that in the meta column of archivedprojects, the percentage of currency is 0 despite being 100% achieved. So it looks like the error is in the exporting of the metadata?

![schermafbeelding 2016-05-18 om 18 15 34](https://cloud.githubusercontent.com/assets/9094522/15366424/8ecbd63c-1d24-11e6-8d1a-fa4d92e25c61.png)

**Comment by ghost** [comment]
I'll look at it later today.

**Comment by ghost** [comment]
Should be fixed now. You must re-import the project because -- indeed -- the data in details.json was incorrect.

Percentages on completed projects should now be reflected here as well.

![screen shot 2016-05-19 at 12 34 54](https://cloud.githubusercontent.com/assets/13518991/15390808/20b8f39c-1dbe-11e6-858f-dfe6d3f68375.png) (my own setup)

**Comment by ghost** [comment]
Looks fine on Spitsgids as well:

https://spitsgids.be/details.json

Closing this now.
